environment:
  pypi_user:
    secure: KKXTfybdjSOuJyfkKtQYVg==
  pypi_pass:
    secure: tCVOa2L8AcyKdru04tVTCw==
  DEPLOY_ONLY: false
  matrix:
    - PYTHON: C:\Python35\python.exe
      platform: Any CPU
      DEPLOY_ONLY: true
    - PYTHON: C:\Python35-x64\python.exe
      platform: x64
      DEPLOY_ONLY: true
    - PYTHON: C:\Python36\python.exe
      platform: Any CPU
    - PYTHON: C:\Python36-x64\python.exe
      platform: x64

cache:
  - '%localappdata%\pip\cache -> setup.py'

init:
  - cmd: "if %APPVEYOR_REPO_TAG%==false if %DEPLOY_ONLY%==true appveyor exit"

install:
  - cmd: '%PYTHON% -m pip install --upgrade pip setuptools wheel twine'

build_script:
  - cmd: '%PYTHON% setup.py build sdist bdist_wheel'

deploy_script:
  - cmd: 'if defined APPVEYOR_REPO_TAG_NAME %PYTHON% -m twine upload -u %pypi_user% -p %pypi_pass% --skip-existing dist/*'
